server:
  port: 8761

spring:
    application:
        name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    serviceUrl:
      defaultZone: http://172.16.210.130:8761/eureka/